
services:
  backend_rds:
    build:
      context: ./backend_rds
    container_name: backend-rds
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend_redis:
    build:
      context: ./backend_redis
    container_name: backend-redis
    ports:
      - "8001:8001"
    depends_on:
      - backend_rds
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - backend_rds
      - backend_redis

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend


volumes:
  pg_data:
