name: Build & Push Backend Redis

on:
  push:
    paths:
      - 'backend_redis/**'
      - '.github/workflows/docker-push-backend-redis.yml'
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push backend-redis image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/backend-redis:$IMAGE_TAG ./backend_redis
          docker push $ECR_REGISTRY/backend-redis:$IMAGE_TAG
